### ISSUE TITLE
Electric field due to dipole moments

### ISSUE THREAD

**Issue by tgakay** [andysim/helpme#56]
Hi Andy,
I have a question regarding reciprocal-space dipole contributions to the electric field (computePRec method). It's the last term in the Eq (49) https://doi.org/10.1063/1.3511713 for electric field due to dipole moments (I guess it's the field due to interaction the dipole's images in other cells?). I'm not an expert in the Ewald summation to judge if the articles cited in the helPME docs have or not the term but I did run some comparison between helPME and another (non-PME) Ewald implementation where this term can be switched off. The results without the term were identical to helPME, which makes me think that this term might be missing. Am I missing something or is there a mistake in the paper by Sala et. al? 

Kind regards,
Alexei

**Comment by andysim** [comment]
Hi, Alexei,

Thanks for reaching out.  I have read the paper you linked, as well as the paper they cite with the original definition, and here is what I think the source of the discrepancy is.

For standard (non-PME) sums, increasing the cutoff to a massive value results in an _conditionally convergent_ sum; that is, the energy will depend on the order of summation of the terms.  Another way of thinking about it is that the crystal has a macroscopic shape and that shape determines the order of summation, which in turn defines the energy.

In Ewald summation (and PME) the standard energy terms are _absolutely convergent_ and there is no ambiguity in the energy.  This can be reconciled with the "brute force" long cutoff answer by realizing that the h=0 term in reciprocal space is ill defined.  There's a term related to the sum of the charges, which vanishes for a neutral system.  Then there's a "surface" term that is related to the macroscopic crystal shape, which is the term you pointed out in Eq (49).

That term is related to the square dipole moment of the whole unit cell, and is usually neglected.  The force resulting from the point dipole contribution is zero, as you point out.  However, if point charges are present, they contribute to the cell's dipole moment and the corresponding force term is proportional to the unit cell dipole.  If a charge goes out of the top of the cell and back into the bottom, due to the periodic boundaries, I think this makes for a discontinuous force and I _think_ it is why this surface term is usually neglected.  The neglect of the surface term is usually motivated by "metallic" or "tinfoil" boundary conditions where we assume an infinite dielectric surrounding the system.  The term that is derived in the paper you referenced looks like the result one gets by assuming cubic boxes arranged in a spherical shape.

I don't think either answer is wrong, it's just a different choice of boundary conditions.  If you'd like the code to compute and add surface terms, I think it will be easy to code.  Choosing the API to be something reasonable might take a little thought, but that is the hardest part.  Please let me know if you agree with my analysis and how you would like to move forwards,

Best regards,

Andy.

**Comment by CisnerosResearch** [comment]
Hi Andy,

This thread and paper have been super interesting to follow. I just wanted to point out that the surface term/PBC is that there are expressions for some specific unit cell shapes that have been derived (e.g. by Hummer), but that may be going way into the reeds (Tom mentioned it briefly in the PME bible 🙂 ).

Best,

Andrés


G. Andrés Cisneros, Ph.D

Professor

Department of Chemistry

Center for Adv. Scientific Computing and Modeling (CASCaM)

University of North Texas

http://chemistry.unt.edu/~CisnerosResearch

andres@unt.edu

he/him/his

________________________________

**Comment by tgakay** [comment]
Hi Andy,
Thank you for your response. I'll leave it as is for now and focus on other things. I do have a feeling that's not related to the surface term (there's no epsilon_sur anywhere near it) but that it comes from differentiating the exp(ikr)*Q^mu product of the electrostatic potential eq(27) in https://doi.org/10.1063/1.481216 (cited by Sala et al.). Though I must admit I did not try to work out the equations myself.
Cheers,
Alexei

**Comment by tgakay** [comment]
The electric field due to dipoles seems to be fine. The problem seems to be in the dipole energy.
